Added the zenodo file with the contributors
earthlab/abc-classroom pull request #269
Opened 2020-09-10 21:36 UTC by nkorinek

Added a zenodo file with all the contributors listed in this issue: https://github.com/earthlab/abc-classroom/issues/252

2020-09-11 21:03 UTC, lwasser commented on .zenodo.json
> +  "contributors": [
@nkorinek can you please list time as a creator as well? he did originally create this package so i think it's important to list him there.

2020-09-11 21:03 UTC, lwasser requested changes
just one small change @nkorinek  and we can merge this!

2020-09-14 18:16 UTC, nkorinek commented
@lwasser moved tim!

2020-09-15 19:22 UTC, lwasser commented
thank you again @nkorinek !!

2020-09-15 19:22 UTC, lwasser approved these changes

2020-09-15 19:23 UTC, merged